repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-toml
      - id: check-case-conflict

  # Rust formatting and linting
  - repo: https://github.com/pre-commit/mirrors-rustfmt
    rev: v1.5.1
    hooks:
      - id: rustfmt
        args: [--edition, "2024", --all]
        files: ^(src/|tests/).*\.rs$

  - repo: https://github.com/pre-commit/mirrors-clippy
    rev: v0.1.67
    hooks:
      - id: clippy
        args: [--all-targets, --all-features, --no-deps]
        files: ^(src/|tests/).*\.rs$

  # Comprehensive Rust quality checks
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
        args: [--all-targets, --all-features]
      - id: cargo-test
        args: [--all-features]
      - id: cargo-doc
        args: [--document-private-items, --no-deps]

  # Security and dependency checking
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            .*\.lock$|
            .*\.toml$|
            .*\.json$|
            .*\.md$|
            .*\.txt$
          )$

  # Documentation formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(md|json|yaml|yml)$
        exclude: |
          (?x)^(
            .*\.lock$|
            Cargo\.lock$
          )$

# Configuration for specific hooks
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
