# Cargo-deny configuration for comprehensive code quality enforcement
# This file enforces strict standards for dependencies, licensing, and security

[advisories]
# Check for unmaintained crates
unmaintained = "warn"
# Check for yanked crates
yanked = "deny"

[licenses]
# Allow specific licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Unicode-3.0",
    "Zlib",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",
]

[sources]
# Allow specific registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# Deny unknown sources
unknown-registry = "deny"
# Allow specific git sources
allow-git = []

[bans]
multiple-versions = "warn"
# Check for multiple versions of the same crate
# Allow wildcard dependencies for internal workspace crates
wildcards = "allow"
